# Generated by Django 5.0.6 on 2024-06-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
